// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace jc.analytics
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class GameItemBuy : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"GameItemBuy\",\"namespace\":\"jc.analytics\",\"fields\":[{\"name\":\"serverEpochMs\",\"type\":\"long\"},{\"name\":\"clientEpochMs\",\"type\":\"long\"},{\"name\":\"sessionId\",\"type\":\"long\"},{\"name\":\"appId\",\"type\":\"int\"},{\"name\":\"userId\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"nonce\",\"type\":{\"type\":\"fixed\",\"name\":\"Nonce\",\"namespace\":\"jc.analytics\",\"size\":16}},{\"name\":\"progress\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"judi\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"customMap\",\"default\":null,\"type\":[\"null\",{\"type\":\"map\",\"values\":[\"string\",\"int\",\"long\",\"bytes\",\"float\",\"double\",\"boolean\"]}]},{\"name\":\"locationId\",\"type\":[\"null\",\"string\"]},{\"name\":\"itemId\",\"type\":[\"null\",\"string\"]},{\"name\":\"itemType\",\"type\":[\"null\",\"string\"]},{\"name\":\"itemsPurchasedQuantity\",\"type\":[\"null\",\"int\"]},{\"name\":\"paymentType\",\"type\":[\"null\",\"string\"]},{\"name\":\"paymentAmount\",\"type\":[\"null\",\"int\"]},{\"name\":\"postPurchaseBalance\",\"type\":[\"null\",\"int\"]}],\"subject\":\"analytics.game-item-buy-value\"}");
		private long _serverEpochMs;
		private long _clientEpochMs;
		private long _sessionId;
		private int _appId;
		private string _userId;
		private jc.analytics.Nonce _nonce;
		private System.Nullable<int> _progress;
		private string _judi;
		private IDictionary<string,System.Object> _customMap;
		private string _locationId;
		private string _itemId;
		private string _itemType;
		private System.Nullable<int> _itemsPurchasedQuantity;
		private string _paymentType;
		private System.Nullable<int> _paymentAmount;
		private System.Nullable<int> _postPurchaseBalance;
		public virtual Schema Schema
		{
			get
			{
				return GameItemBuy._SCHEMA;
			}
		}
		public long serverEpochMs
		{
			get
			{
				return this._serverEpochMs;
			}
			set
			{
				this._serverEpochMs = value;
			}
		}
		public long clientEpochMs
		{
			get
			{
				return this._clientEpochMs;
			}
			set
			{
				this._clientEpochMs = value;
			}
		}
		public long sessionId
		{
			get
			{
				return this._sessionId;
			}
			set
			{
				this._sessionId = value;
			}
		}
		public int appId
		{
			get
			{
				return this._appId;
			}
			set
			{
				this._appId = value;
			}
		}
		public string userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				this._userId = value;
			}
		}
		public jc.analytics.Nonce nonce
		{
			get
			{
				return this._nonce;
			}
			set
			{
				this._nonce = value;
			}
		}
		public System.Nullable<int> progress
		{
			get
			{
				return this._progress;
			}
			set
			{
				this._progress = value;
			}
		}
		public string judi
		{
			get
			{
				return this._judi;
			}
			set
			{
				this._judi = value;
			}
		}
		public IDictionary<string,System.Object> customMap
		{
			get
			{
				return this._customMap;
			}
			set
			{
				this._customMap = value;
			}
		}
		public string locationId
		{
			get
			{
				return this._locationId;
			}
			set
			{
				this._locationId = value;
			}
		}
		public string itemId
		{
			get
			{
				return this._itemId;
			}
			set
			{
				this._itemId = value;
			}
		}
		public string itemType
		{
			get
			{
				return this._itemType;
			}
			set
			{
				this._itemType = value;
			}
		}
		public System.Nullable<int> itemsPurchasedQuantity
		{
			get
			{
				return this._itemsPurchasedQuantity;
			}
			set
			{
				this._itemsPurchasedQuantity = value;
			}
		}
		public string paymentType
		{
			get
			{
				return this._paymentType;
			}
			set
			{
				this._paymentType = value;
			}
		}
		public System.Nullable<int> paymentAmount
		{
			get
			{
				return this._paymentAmount;
			}
			set
			{
				this._paymentAmount = value;
			}
		}
		public System.Nullable<int> postPurchaseBalance
		{
			get
			{
				return this._postPurchaseBalance;
			}
			set
			{
				this._postPurchaseBalance = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.serverEpochMs;
			case 1: return this.clientEpochMs;
			case 2: return this.sessionId;
			case 3: return this.appId;
			case 4: return this.userId;
			case 5: return this.nonce;
			case 6: return this.progress;
			case 7: return this.judi;
			case 8: return this.customMap;
			case 9: return this.locationId;
			case 10: return this.itemId;
			case 11: return this.itemType;
			case 12: return this.itemsPurchasedQuantity;
			case 13: return this.paymentType;
			case 14: return this.paymentAmount;
			case 15: return this.postPurchaseBalance;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.serverEpochMs = (System.Int64)fieldValue; break;
			case 1: this.clientEpochMs = (System.Int64)fieldValue; break;
			case 2: this.sessionId = (System.Int64)fieldValue; break;
			case 3: this.appId = (System.Int32)fieldValue; break;
			case 4: this.userId = (System.String)fieldValue; break;
			case 5: this.nonce = (jc.analytics.Nonce)fieldValue; break;
			case 6: this.progress = (System.Nullable<int>)fieldValue; break;
			case 7: this.judi = (System.String)fieldValue; break;
			case 8: this.customMap = (IDictionary<string,System.Object>)fieldValue; break;
			case 9: this.locationId = (System.String)fieldValue; break;
			case 10: this.itemId = (System.String)fieldValue; break;
			case 11: this.itemType = (System.String)fieldValue; break;
			case 12: this.itemsPurchasedQuantity = (System.Nullable<int>)fieldValue; break;
			case 13: this.paymentType = (System.String)fieldValue; break;
			case 14: this.paymentAmount = (System.Nullable<int>)fieldValue; break;
			case 15: this.postPurchaseBalance = (System.Nullable<int>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
