// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen.exe, version 0.9.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace jc.analytics
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
	public partial class AppError : ISpecificRecord
	{
		public static Schema _SCHEMA = Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"AppError\",\"namespace\":\"jc.analytics\",\"fields\":[{\"name\":\"serverEpochMs\",\"type\":\"long\"},{\"name\":\"clientEpochMs\",\"type\":\"long\"},{\"name\":\"sessionId\",\"type\":\"long\"},{\"name\":\"appId\",\"type\":\"int\"},{\"name\":\"userId\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"nonce\",\"type\":{\"type\":\"fixed\",\"name\":\"Nonce\",\"namespace\":\"jc.analytics\",\"size\":16}},{\"name\":\"progress\",\"default\":null,\"type\":[\"null\",\"int\"]},{\"name\":\"judi\",\"default\":null,\"type\":[\"null\",\"string\"]},{\"name\":\"customMap\",\"default\":null,\"type\":[\"null\",{\"type\":\"map\",\"values\":[\"string\",\"int\",\"long\",\"bytes\",\"float\",\"double\",\"boolean\"]}]},{\"name\":\"error\",\"type\":[\"null\",\"string\"]},{\"name\":\"errorDescription\",\"type\":[\"null\",\"string\"]}],\"subject\":\"analytics.app-error-value\"}");
		private long _serverEpochMs;
		private long _clientEpochMs;
		private long _sessionId;
		private int _appId;
		private string _userId;
		private jc.analytics.Nonce _nonce;
		private System.Nullable<int> _progress;
		private string _judi;
		private IDictionary<string,System.Object> _customMap;
		private string _error;
		private string _errorDescription;
		public virtual Schema Schema
		{
			get
			{
				return AppError._SCHEMA;
			}
		}
		public long serverEpochMs
		{
			get
			{
				return this._serverEpochMs;
			}
			set
			{
				this._serverEpochMs = value;
			}
		}
		public long clientEpochMs
		{
			get
			{
				return this._clientEpochMs;
			}
			set
			{
				this._clientEpochMs = value;
			}
		}
		public long sessionId
		{
			get
			{
				return this._sessionId;
			}
			set
			{
				this._sessionId = value;
			}
		}
		public int appId
		{
			get
			{
				return this._appId;
			}
			set
			{
				this._appId = value;
			}
		}
		public string userId
		{
			get
			{
				return this._userId;
			}
			set
			{
				this._userId = value;
			}
		}
		public jc.analytics.Nonce nonce
		{
			get
			{
				return this._nonce;
			}
			set
			{
				this._nonce = value;
			}
		}
		public System.Nullable<int> progress
		{
			get
			{
				return this._progress;
			}
			set
			{
				this._progress = value;
			}
		}
		public string judi
		{
			get
			{
				return this._judi;
			}
			set
			{
				this._judi = value;
			}
		}
		public IDictionary<string,System.Object> customMap
		{
			get
			{
				return this._customMap;
			}
			set
			{
				this._customMap = value;
			}
		}
		public string error
		{
			get
			{
				return this._error;
			}
			set
			{
				this._error = value;
			}
		}
		public string errorDescription
		{
			get
			{
				return this._errorDescription;
			}
			set
			{
				this._errorDescription = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.serverEpochMs;
			case 1: return this.clientEpochMs;
			case 2: return this.sessionId;
			case 3: return this.appId;
			case 4: return this.userId;
			case 5: return this.nonce;
			case 6: return this.progress;
			case 7: return this.judi;
			case 8: return this.customMap;
			case 9: return this.error;
			case 10: return this.errorDescription;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.serverEpochMs = (System.Int64)fieldValue; break;
			case 1: this.clientEpochMs = (System.Int64)fieldValue; break;
			case 2: this.sessionId = (System.Int64)fieldValue; break;
			case 3: this.appId = (System.Int32)fieldValue; break;
			case 4: this.userId = (System.String)fieldValue; break;
			case 5: this.nonce = (jc.analytics.Nonce)fieldValue; break;
			case 6: this.progress = (System.Nullable<int>)fieldValue; break;
			case 7: this.judi = (System.String)fieldValue; break;
			case 8: this.customMap = (IDictionary<string,System.Object>)fieldValue; break;
			case 9: this.error = (System.String)fieldValue; break;
			case 10: this.errorDescription = (System.String)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
